#!/usr/bin/env python3
"""
train_ur5e_dnn.py

Train a feedforward DNN to predict UR5e joint angles from end-effector pose.
Loads the CSV generated by generate_ur5e_fk_ik_dataset.py, auto-detects
position-only vs full-pose mode, trains, evaluates, and saves artifacts.

Usage:
    python train_ur5e_dnn.py
    python train_ur5e_dnn.py --csv my_data.csv --epochs 200 --batch_size 128
"""

import argparse
import os
import pickle
import time

import matplotlib
matplotlib.use("Agg")  # non-interactive backend for saving plots
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import DataLoader, TensorDataset

# ============================================================================
# Defaults (easy to change)
# ============================================================================
DEFAULT_CSV = "ur5e_ik_dataset.csv"
DEFAULT_EPOCHS = 100
DEFAULT_BATCH_SIZE = 64
DEFAULT_LR = 1e-3
DEFAULT_SEED = 42
DEFAULT_PATIENCE = 15

POSITION_COLS = ["x", "y", "z"]
ROTATION_COLS = ["r11", "r12", "r13", "r21", "r22", "r23", "r31", "r32", "r33"]
JOINT_COLS = ["q1", "q2", "q3", "q4", "q5", "q6"]

# ============================================================================
# Reproducibility
# ============================================================================

def set_seed(seed: int):
    """Set random seeds for reproducibility across numpy, torch, and CUDA."""
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# ============================================================================
# Data loading and column detection
# ============================================================================

def detect_columns(df):
    """Auto-detect input columns (position-only or full-pose) and validate.

    Returns
    -------
    input_cols : list of str
    mode       : str  ("position" or "pose")
    """
    has_position = all(c in df.columns for c in POSITION_COLS)
    has_rotation = all(c in df.columns for c in ROTATION_COLS)
    has_joints = all(c in df.columns for c in JOINT_COLS)

    if not has_position:
        raise ValueError(f"Missing position columns. Expected {POSITION_COLS}, "
                         f"got {list(df.columns)}")
    if not has_joints:
        raise ValueError(f"Missing joint columns. Expected {JOINT_COLS}, "
                         f"got {list(df.columns)}")

    if has_rotation:
        input_cols = POSITION_COLS + ROTATION_COLS
        mode = "pose"
    else:
        input_cols = POSITION_COLS
        mode = "position"

    return input_cols, mode


def load_and_prepare_data(csv_path):
    """Load CSV, detect columns, drop NaNs, return X, Y arrays and metadata.

    Returns
    -------
    X          : ndarray (N, input_dim)
    Y          : ndarray (N, 6)
    input_cols : list of str
    mode       : str
    """
    if not os.path.isfile(csv_path):
        raise FileNotFoundError(f"Dataset not found: {csv_path}")

    df = pd.read_csv(csv_path)
    print(f"Loaded {len(df)} rows from {csv_path}")
    print(f"Columns: {list(df.columns)}")

    input_cols, mode = detect_columns(df)
    print(f"Detected mode: {mode}  (input_dim={len(input_cols)})")

    # Check for NaNs
    nan_count = df[input_cols + JOINT_COLS].isna().sum().sum()
    if nan_count > 0:
        print(f"WARNING: dropping {nan_count} NaN entries")
        df = df.dropna(subset=input_cols + JOINT_COLS)

    X = df[input_cols].values.astype(np.float32)
    Y = df[JOINT_COLS].values.astype(np.float32)

    print(f"Dataset: {X.shape[0]} samples, input_dim={X.shape[1]}, output_dim={Y.shape[1]}")
    return X, Y, input_cols, mode

# ============================================================================
# Splitting and scaling
# ============================================================================

def split_data(X, Y, seed=42):
    """Split into 80/10/10 train/val/test sets.

    Returns
    -------
    (X_train, X_val, X_test, Y_train, Y_val, Y_test)
    """
    X_train, X_temp, Y_train, Y_temp = train_test_split(
        X, Y, test_size=0.2, random_state=seed)
    X_val, X_test, Y_val, Y_test = train_test_split(
        X_temp, Y_temp, test_size=0.5, random_state=seed)

    print(f"Split: train={len(X_train)}, val={len(X_val)}, test={len(X_test)}")
    return X_train, X_val, X_test, Y_train, Y_val, Y_test


def fit_scalers(X_train, Y_train):
    """Fit StandardScalers on training data only.

    Returns
    -------
    input_scaler  : StandardScaler
    output_scaler : StandardScaler
    """
    input_scaler = StandardScaler().fit(X_train)
    output_scaler = StandardScaler().fit(Y_train)
    return input_scaler, output_scaler


def transform_data(X, Y, input_scaler, output_scaler):
    """Apply fitted scalers to X and Y.

    Returns
    -------
    X_scaled : ndarray
    Y_scaled : ndarray
    """
    X_scaled = input_scaler.transform(X).astype(np.float32)
    Y_scaled = output_scaler.transform(Y).astype(np.float32)
    return X_scaled, Y_scaled

# ============================================================================
# Model
# ============================================================================

class IKNet(nn.Module):
    """Feedforward MLP for inverse kinematics prediction."""

    def __init__(self, input_dim, output_dim=6, hidden_sizes=(512, 512, 256, 256)):
        super().__init__()
        layers = []
        prev = input_dim
        for h in hidden_sizes:
            layers.append(nn.Linear(prev, h))
            layers.append(nn.ReLU())
            prev = h
        layers.append(nn.Linear(prev, output_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


def build_model(input_dim, output_dim=6):
    """Build the IKNet and print parameter count."""
    model = IKNet(input_dim, output_dim)
    num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"\nModel architecture:\n{model}")
    print(f"Trainable parameters: {num_params:,}\n")
    return model

# ============================================================================
# Training
# ============================================================================

def make_dataloader(X, Y, batch_size, shuffle=True):
    """Wrap numpy arrays into a PyTorch DataLoader."""
    ds = TensorDataset(torch.from_numpy(X), torch.from_numpy(Y))
    return DataLoader(ds, batch_size=batch_size, shuffle=shuffle)


def train_model(model, train_loader, val_loader, epochs, lr, patience, device):
    """Train with Adam + MSE, early stopping on validation loss.

    Returns
    -------
    history : dict with keys "epoch", "train_loss", "val_loss"
    """
    model.to(device)
    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    best_val_loss = float("inf")
    best_state = None
    patience_counter = 0

    history = {"epoch": [], "train_loss": [], "val_loss": []}

    print(f"Training on {device} for up to {epochs} epochs  "
          f"(patience={patience}, lr={lr})")
    print("-" * 70)

    t0 = time.time()

    for epoch in range(1, epochs + 1):
        # --- Training ---
        model.train()
        train_loss_sum = 0.0
        train_count = 0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            pred = model(xb)
            loss = criterion(pred, yb)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            train_loss_sum += loss.item() * xb.size(0)
            train_count += xb.size(0)
        train_loss = train_loss_sum / train_count

        # --- Validation ---
        model.eval()
        val_loss_sum = 0.0
        val_count = 0
        with torch.no_grad():
            for xb, yb in val_loader:
                xb, yb = xb.to(device), yb.to(device)
                pred = model(xb)
                loss = criterion(pred, yb)
                val_loss_sum += loss.item() * xb.size(0)
                val_count += xb.size(0)
        val_loss = val_loss_sum / val_count

        history["epoch"].append(epoch)
        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)

        # --- Early stopping ---
        improved = ""
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            patience_counter = 0
            improved = " *"
        else:
            patience_counter += 1

        elapsed = time.time() - t0
        print(f"Epoch {epoch:>4d}/{epochs}  "
              f"train_loss={train_loss:.6f}  val_loss={val_loss:.6f}  "
              f"({elapsed:.1f}s){improved}")

        if patience_counter >= patience:
            print(f"\nEarly stopping at epoch {epoch} "
                  f"(no improvement for {patience} epochs)")
            break

    # Restore best weights
    if best_state is not None:
        model.load_state_dict(best_state)
    model.to(device)

    print(f"\nBest validation loss: {best_val_loss:.6f}")
    return history

# ============================================================================
# Evaluation
# ============================================================================

def evaluate_model(model, test_loader, output_scaler, device):
    """Evaluate on the test set and print metrics in original (radian) units.

    Returns
    -------
    metrics : dict
    """
    model.eval()
    all_preds = []
    all_targets = []

    with torch.no_grad():
        for xb, yb in test_loader:
            xb = xb.to(device)
            pred = model(xb).cpu().numpy()
            all_preds.append(pred)
            all_targets.append(yb.numpy())

    preds_scaled = np.vstack(all_preds)
    targets_scaled = np.vstack(all_targets)

    # Inverse-transform back to radians
    preds = output_scaler.inverse_transform(preds_scaled)
    targets = output_scaler.inverse_transform(targets_scaled)

    errors = preds - targets                      # (N, 6)
    mse = np.mean(errors ** 2)
    rmse = np.sqrt(mse)
    mae = np.mean(np.abs(errors))
    per_joint_mae = np.mean(np.abs(errors), axis=0)
    joint_norm = np.mean(np.linalg.norm(errors, axis=1))

    print("\n" + "=" * 60)
    print("TEST SET EVALUATION  (original radian units)")
    print("=" * 60)
    print(f"  MSE                  : {mse:.6f}")
    print(f"  RMSE                 : {rmse:.6f}")
    print(f"  Mean Absolute Error  : {mae:.6f}")
    print(f"  Mean joint-norm error: {joint_norm:.6f}")
    print(f"  Per-joint MAE (rad)  :")
    for i, name in enumerate(JOINT_COLS):
        print(f"    {name}: {per_joint_mae[i]:.6f}")
    print("=" * 60)

    metrics = {
        "mse": mse, "rmse": rmse, "mae": mae,
        "joint_norm": joint_norm,
        "per_joint_mae": dict(zip(JOINT_COLS, per_joint_mae.tolist())),
    }
    return metrics, preds, targets

# ============================================================================
# Artifact saving
# ============================================================================

def save_artifacts(model, input_scaler, output_scaler, history,
                   out_dir=".", prefix="ur5e_dnn"):
    """Save model weights, scalers, training history CSV, and loss plot."""

    # Model weights
    model_path = os.path.join(out_dir, f"{prefix}_best.pt")
    torch.save(model.state_dict(), model_path)
    print(f"Saved model weights   -> {model_path}")

    # Scalers
    in_sc_path = os.path.join(out_dir, "input_scaler.pkl")
    out_sc_path = os.path.join(out_dir, "output_scaler.pkl")
    with open(in_sc_path, "wb") as f:
        pickle.dump(input_scaler, f)
    with open(out_sc_path, "wb") as f:
        pickle.dump(output_scaler, f)
    print(f"Saved input scaler    -> {in_sc_path}")
    print(f"Saved output scaler   -> {out_sc_path}")

    # History CSV
    hist_path = os.path.join(out_dir, "training_history.csv")
    pd.DataFrame(history).to_csv(hist_path, index=False)
    print(f"Saved training history -> {hist_path}")

    # Loss curve
    plot_path = os.path.join(out_dir, "loss_curve.png")
    plot_loss_curve(history, plot_path)
    print(f"Saved loss curve      -> {plot_path}")


def plot_loss_curve(history, save_path):
    """Plot training and validation loss vs epoch and save to file."""
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(history["epoch"], history["train_loss"], label="Train Loss")
    ax.plot(history["epoch"], history["val_loss"], label="Val Loss")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("MSE Loss (scaled)")
    ax.set_title("Training & Validation Loss")
    ax.legend()
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(save_path, dpi=150)
    plt.close(fig)


def plot_pred_vs_true(preds, targets, joint_idx=0, save_path="pred_vs_true_q1.png"):
    """Scatter plot of predicted vs true for one joint."""
    fig, ax = plt.subplots(figsize=(6, 6))
    ax.scatter(targets[:, joint_idx], preds[:, joint_idx],
               s=4, alpha=0.4, edgecolors="none")
    lims = [min(targets[:, joint_idx].min(), preds[:, joint_idx].min()) - 0.1,
            max(targets[:, joint_idx].max(), preds[:, joint_idx].max()) + 0.1]
    ax.plot(lims, lims, "r--", linewidth=1, label="perfect")
    ax.set_xlabel(f"True {JOINT_COLS[joint_idx]} (rad)")
    ax.set_ylabel(f"Predicted {JOINT_COLS[joint_idx]} (rad)")
    ax.set_title(f"Predicted vs True — {JOINT_COLS[joint_idx]}")
    ax.legend()
    ax.set_aspect("equal", "box")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(save_path, dpi=150)
    plt.close(fig)

# ============================================================================
# Main
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Train a DNN for UR5e inverse kinematics prediction.")
    parser.add_argument("--csv", type=str, default=DEFAULT_CSV,
                        help=f"Path to dataset CSV (default: {DEFAULT_CSV})")
    parser.add_argument("--epochs", type=int, default=DEFAULT_EPOCHS,
                        help=f"Max training epochs (default: {DEFAULT_EPOCHS})")
    parser.add_argument("--batch_size", type=int, default=DEFAULT_BATCH_SIZE,
                        help=f"Mini-batch size (default: {DEFAULT_BATCH_SIZE})")
    parser.add_argument("--lr", type=float, default=DEFAULT_LR,
                        help=f"Learning rate (default: {DEFAULT_LR})")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED,
                        help=f"Random seed (default: {DEFAULT_SEED})")
    parser.add_argument("--patience", type=int, default=DEFAULT_PATIENCE,
                        help=f"Early stopping patience (default: {DEFAULT_PATIENCE})")
    parser.add_argument("--out_dir", type=str, default=".",
                        help="Directory for output artifacts (default: cwd)")
    args = parser.parse_args()

    set_seed(args.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}\n")

    # --- Data ---
    X, Y, input_cols, mode = load_and_prepare_data(args.csv)
    X_train, X_val, X_test, Y_train, Y_val, Y_test = split_data(X, Y, seed=args.seed)

    input_scaler, output_scaler = fit_scalers(X_train, Y_train)
    X_train_s, Y_train_s = transform_data(X_train, Y_train, input_scaler, output_scaler)
    X_val_s, Y_val_s = transform_data(X_val, Y_val, input_scaler, output_scaler)
    X_test_s, Y_test_s = transform_data(X_test, Y_test, input_scaler, output_scaler)

    train_loader = make_dataloader(X_train_s, Y_train_s, args.batch_size, shuffle=True)
    val_loader = make_dataloader(X_val_s, Y_val_s, args.batch_size, shuffle=False)
    test_loader = make_dataloader(X_test_s, Y_test_s, args.batch_size, shuffle=False)

    # --- Model ---
    input_dim = X_train_s.shape[1]
    model = build_model(input_dim, output_dim=6)

    # --- Train ---
    history = train_model(model, train_loader, val_loader,
                          epochs=args.epochs, lr=args.lr,
                          patience=args.patience, device=device)

    # --- Evaluate ---
    metrics, preds, targets = evaluate_model(model, test_loader, output_scaler, device)

    # --- Save artifacts ---
    os.makedirs(args.out_dir, exist_ok=True)
    save_artifacts(model, input_scaler, output_scaler, history, out_dir=args.out_dir)

    # Bonus diagnostic plot: predicted vs true for q1
    pvt_path = os.path.join(args.out_dir, "pred_vs_true_q1.png")
    plot_pred_vs_true(preds, targets, joint_idx=0, save_path=pvt_path)
    print(f"Saved pred-vs-true    -> {pvt_path}")

    print("\nDone.")


if __name__ == "__main__":
    main()
